### PR TITLE
Add /block/headers GET/POST endpoints + tests and mock data

### PR DESCRIPTION
**Pull request by rkalis**

### CODE REVIEW

**Comment by rkalis** [comment]
I actually managed to figure out the test script as well by looking at the env variables in the test code. All tests were passing for me before sybmitting the PR. I just re-ran the tests, and they're still passing on my end. Which tests are failing for you?

**Comment by christroutner** [comment]
Oh?! That's strange.

When I execute the above shell script on this branch, I get the following errors:

```
1) #ElectrumX Router
       #_transactionDetailsFromElectrum
         should return error object for invalid txid:
     AssertionError: expected { code: 1, message: 'Invalid tx hash' } to be an instance of Error
      at Context.<anonymous> (test/v3/a01-electrumx.js:462:14)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  2) #ElectrumX Router
       #getTransactionDetails
         should return error object for invalid txid:

      HTTP status code 400 expected.
      + expected - actual

      -200
      +400
      
      at expectRouteError (test/v3/a01-electrumx.js:36:10)
      at Context.<anonymous> (test/v3/a01-electrumx.js:520:7)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  3) #ElectrumX Router
       #_blockHeadersFromElectrum
         should return error object for invalid block height:
     TypeError: Cannot read property 'match' of undefined
      at Electrum._blockHeadersFromElectrum (src/routes/v3/electrumx.js:518:46)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Context.<anonymous> (test/v3/a01-electrumx.js:679:22)

  4) #ElectrumX Router
       #_blockHeadersFromElectrum
         should return error object for invalid count:
     TypeError: Cannot read property 'match' of undefined
      at Electrum._blockHeadersFromElectrum (src/routes/v3/electrumx.js:518:46)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Context.<anonymous> (test/v3/a01-electrumx.js:694:22)

  5) #ElectrumX Router
       #getBlockheaders
         should return error object for invalid height:
     AssertionError: expected 'Cannot read property \'match\' of undefined' to include 'Invalid height'
      at expectRouteError (test/v3/a01-electrumx.js:39:10)
      at Context.<anonymous> (test/v3/a01-electrumx.js:773:7)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  6) #ElectrumX Router
       #blockHeadersBulk
         should NOT throw 400 error for an invalid height:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/v3/a01-electrumx.js:838:14)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by christroutner** [comment]
So [that first test](https://github.com/Permissionless-Software-Foundation/bch-api/blob/7-electrum-block-header/test/v3/a01-electrumx.js#L450-L458) seems strange to me. Because the TXID used doesn't exist on either mainnet or testnet:

https://explorer.bitcoin.com/bch/search/4db095f34d632a4daf942142c291f1f2abb5ba2e1ccac919d85bdc2f671fb25

**Comment by rkalis** [comment]
Yeah it's a test for an invalid tx hash. Let me see if I can figure out why the tests are failing for you but not me though 🤔

**Comment by rkalis** [comment]
Some of these failures are also from the previous 'transaction details' PR. All of the failures seem to be related to the check against `instanceof Error`. I think I figured out what's up. I was locally running with `yarn`, so it resolved electrum-cash to `1.2.0`, while the package-lock resolved it to `1.0.1`.  In the earlier version the returned error was not an instance of `Error`. I updated the electrum-cash version in the package and package-lock. I'm thinking the tests should succeed on your end now as well (after re-running `npm install`).

**Comment by christroutner** [comment]
Awesome! You nailed it @rkalis. Thank you for dogging that issue and pushing through.

**Comment by christroutner** [comment]
This PR resolves #7

**Comment by rkalis** [comment]
Awesome! As a side note: it might be good to upgrade to v2 of electrum-cash some time in the future.

**Comment by christroutner** [comment]
:tada: This PR is included in version 1.17.9 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
